version: "3"

services:

  postgresql:
    image: bitnami/postgresql:15
    restart: always
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=${DB_USERNAME:?}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:?}
      - POSTGRESQL_DATABASE=hakro-portal
      - POSTGRESQL_REPLICATION_USER=${REPLICATION_DB_USERNAME:?}
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_DB_PASSWORD:?}
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD:?}
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
    networks:
      - hakro-portal
    volumes:
      - postgresql_data:/bitnami/postgresql

  postgresql-replication:
    image: bitnami/postgresql:15.3.0
    restart: always
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgresql
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=${DB_USERNAME:?}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:?}
      - POSTGRESQL_REPLICATION_USER=${REPLICATION_DB_USERNAME:?}
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_DB_PASSWORD:?}
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD:?}
    networks:
      - hakro-portal
    volumes:
      - postgresql_data-replication:/bitnami/postgresql
    depends_on:
      - postgresql

  pgadmin:
    image: dpage/pgadmin4:7.3
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USERNAME:?}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:?}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="HAKRO"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
      - SCRIPT_NAME=/pgadmin4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin4.rule=PathPrefix(`/pgadmin4`)"
      - "traefik.http.routers.pgadmin4.entrypoints=websecure"
      - "traefik.http.routers.pgadmin4.tls=true"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - hakro-portal
    depends_on:
      - postgresql
      - postgresql-replication

volumes:
  postgresql_data:
    driver: local
  postgresql_data-replication:
    driver: local
  pgadmin:
    driver: local

networks:
  hakro-portal:
    name: hakro-portal-network
    external: true
