version: "3"

services:

  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hakro-ll
      - POSTGRES_PASSWORD=Hakro!1969
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - hakro-td

volumes:
  postgres_data:
    driver: local

networks:
  hakro-td:
    name: hakro-td-network
    driver: bridge
