version: "3"

services:

  postgres:
    image: postgres:15-alpine
    environment:
      - "POSTGRES_USER=hakro-ll"
      - "POSTGRES_PASSWORD=Hakro!1969"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.tls=false"
    networks:
      - hakro-td

volumes:
  postgres_data:
    driver: local

networks:
  hakro-td:
    name: hakro-td-network
    external: true
