version: "3"

services:

  postgres:
    image: bitnami/postgresql:15
    restart: always
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=${DB_USERNAME:?}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:?}
      - POSTGRESQL_DATABASE=hakro-ll
      - POSTGRESQL_REPLICATION_USER=${REPLICATION_DB_USERNAME:?}
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_DB_PASSWORD:?}
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.tls=false"
    networks:
      - hakro-td
    volumes:
      - postgres_data:/bitnami/postgresql

  postgres-replication:
    image: bitnami/postgresql:15
    restart: always
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgres
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=${REPLICATION_DB_USERNAME:?}
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_DB_PASSWORD:?}
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - hakro-td
    volumes:
      - postgres_data-replication:/bitnami/postgresql
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:6.16
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${pguser:?}
      - PGADMIN_DEFAULT_PASSWORD=${pgadminpass:?}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="HAKRO"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - hakro-td
    depends_on:
      - postgres
      - postgres-replication
    ports:
      - "8099:80"

volumes:
  postgres_data:
    driver: local
  postgres_data-replication:
    driver: local
  pgadmin:
    driver: local

networks:
  hakro-td:
    name: hakro-td-network
    external: true
